services:
  backend:
    build: ./backend
    container_name: toxic-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: toxic-frontend
    ports:
      - "8501:8501"
    environment:
      # Here we tell the frontend to talk to the 'backend' service defined above
      - API_URL=http://backend:8000/predict
    depends_on:
      - backend